# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagepoll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='display_side',
            field=models.CharField(max_length=2),
        ),
    ]
