# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagepoll', '0002_auto_20170802_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='display_side',
            field=models.CharField(default='l', max_length=2),
        ),
    ]
