# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 20:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagepoll', '0003_auto_20170802_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='display_side',
            field=models.CharField(max_length=1),
        ),
    ]
