# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagepoll', '0004_auto_20170802_2016'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='display_side',
            new_name='side',
        ),
    ]
